# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_hand_controller

  left_hand_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - finger_l_joint1
      - finger_l_joint2
      - finger_l_joint3
      - finger_l_joint4
      - finger_l_joint5
      - finger_l_joint6
      - finger_l_joint7
      - finger_l_joint8
      - finger_l_joint9
      - finger_l_joint10
      - finger_l_joint11
      - finger_l_joint12
      - finger_l_joint13
      - finger_l_joint14
      - finger_l_joint15
      - finger_l_joint16
      - finger_l_joint17
      - finger_l_joint18
      - finger_l_joint19
      - finger_l_joint20
