/**:
  controller_manager:
    ros__parameters:
      use_sim_time: False
      update_rate: 200  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      hand_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      effort_controller:
        type: effort_controllers/JointGroupEffortController

      position_controller:
        type: position_controllers/JointGroupPositionController

# /**:
#   hand_controller:
#     ros__parameters:
#       joints:
#         - finger_joint_1
#         - finger_joint_2
#         - finger_joint_3
#         - finger_joint_4
#         - finger_joint_5
#         - finger_joint_6
#         - finger_joint_7
#         - finger_joint_8
#         - finger_joint_9
#         - finger_joint_10
#         - finger_joint_11
#         - finger_joint_12
#         - finger_joint_13
#         - finger_joint_14
#         - finger_joint_15
#         - finger_joint_16
#         - finger_joint_17
#         - finger_joint_18
#         - finger_joint_19
#         - finger_joint_20
#       command_interfaces:
#         - position
#       state_interfaces:
#         - position
#         - velocity
#       allow_nonzero_velocity_at_trajectory_end: true
#       allow_partial_joints_goal: true
/**:
  position_controller:
    ros__parameters:
      joints:
        - finger_joint_1
        - finger_joint_2
        - finger_joint_3
        - finger_joint_4
        - finger_joint_5
        - finger_joint_6
        - finger_joint_7
        - finger_joint_8
        - finger_joint_9
        - finger_joint_10
        - finger_joint_11
        - finger_joint_12
        - finger_joint_13
        - finger_joint_14
        - finger_joint_15
        - finger_joint_16
        - finger_joint_17
        - finger_joint_18
        - finger_joint_19
        - finger_joint_20

/**:
  effort_controller:
    ros__parameters:
      joints:
        - finger_joint_1
        - finger_joint_2
        - finger_joint_3
        - finger_joint_4
        - finger_joint_5
        - finger_joint_6
        - finger_joint_7
        - finger_joint_8
        - finger_joint_9
        - finger_joint_10
        - finger_joint_11
        - finger_joint_12
        - finger_joint_13
        - finger_joint_14
        - finger_joint_15
        - finger_joint_16
        - finger_joint_17
        - finger_joint_18
        - finger_joint_19
        - finger_joint_20