/**:
  controller_manager:
    ros__parameters:
      use_sim_time: False
      update_rate: 300  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      left_hand_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      right_hand_controller:
        type: joint_trajectory_controller/JointTrajectoryController

      left_effort_controller:
        type: effort_controllers/JointGroupEffortController

      right_effort_controller:
        type: effort_controllers/JointGroupEffortController

      left_position_controller:
        type: position_controllers/JointGroupPositionController

      right_position_controller:
        type: position_controllers/JointGroupPositionController

/**:
  left_hand_controller:
    ros__parameters:
      joints:
        - finger_l_joint1
        - finger_l_joint2
        - finger_l_joint3
        - finger_l_joint4
        - finger_l_joint5
        - finger_l_joint6
        - finger_l_joint7
        - finger_l_joint8
        - finger_l_joint9
        - finger_l_joint10
        - finger_l_joint11
        - finger_l_joint12
        - finger_l_joint13
        - finger_l_joint14
        - finger_l_joint15
        - finger_l_joint16
        - finger_l_joint17
        - finger_l_joint18
        - finger_l_joint19
        - finger_l_joint20
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true

/**:
  right_hand_controller:
    ros__parameters:
      joints:
        - finger_r_joint1
        - finger_r_joint2
        - finger_r_joint3
        - finger_r_joint4
        - finger_r_joint5
        - finger_r_joint6
        - finger_r_joint7
        - finger_r_joint8
        - finger_r_joint9
        - finger_r_joint10
        - finger_r_joint11
        - finger_r_joint12
        - finger_r_joint13
        - finger_r_joint14
        - finger_r_joint15
        - finger_r_joint16
        - finger_r_joint17
        - finger_r_joint18
        - finger_r_joint19
        - finger_r_joint20
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      allow_nonzero_velocity_at_trajectory_end: true
      allow_partial_joints_goal: true

/**:
  left_position_controller:
    ros__parameters:
      joints:
        - finger_l_joint1
        - finger_l_joint2
        - finger_l_joint3
        - finger_l_joint4
        - finger_l_joint5
        - finger_l_joint6
        - finger_l_joint7
        - finger_l_joint8
        - finger_l_joint9
        - finger_l_joint10
        - finger_l_joint11
        - finger_l_joint12
        - finger_l_joint13
        - finger_l_joint14
        - finger_l_joint15
        - finger_l_joint16
        - finger_l_joint17
        - finger_l_joint18
        - finger_l_joint19
        - finger_l_joint20

/**:
  right_position_controller:
    ros__parameters:
      joints:
        - finger_r_joint1
        - finger_r_joint2
        - finger_r_joint3
        - finger_r_joint4
        - finger_r_joint5
        - finger_r_joint6
        - finger_r_joint7
        - finger_r_joint8
        - finger_r_joint9
        - finger_r_joint10
        - finger_r_joint11
        - finger_r_joint12
        - finger_r_joint13
        - finger_r_joint14
        - finger_r_joint15
        - finger_r_joint16
        - finger_r_joint17
        - finger_r_joint18
        - finger_r_joint19
        - finger_r_joint20

/**:
  left_effort_controller:
    ros__parameters:
      joints:
        - finger_l_joint1
        - finger_l_joint2
        - finger_l_joint3
        - finger_l_joint4
        - finger_l_joint5
        - finger_l_joint6
        - finger_l_joint7
        - finger_l_joint8
        - finger_l_joint9
        - finger_l_joint10
        - finger_l_joint11
        - finger_l_joint12
        - finger_l_joint13
        - finger_l_joint14
        - finger_l_joint15
        - finger_l_joint16
        - finger_l_joint17
        - finger_l_joint18
        - finger_l_joint19
        - finger_l_joint20

/**:
  right_effort_controller:
    ros__parameters:
      joints:
        - finger_r_joint1
        - finger_r_joint2
        - finger_r_joint3
        - finger_r_joint4
        - finger_r_joint5
        - finger_r_joint6
        - finger_r_joint7
        - finger_r_joint8
        - finger_r_joint9
        - finger_r_joint10
        - finger_r_joint11
        - finger_r_joint12
        - finger_r_joint13
        - finger_r_joint14
        - finger_r_joint15
        - finger_r_joint16
        - finger_r_joint17
        - finger_r_joint18
        - finger_r_joint19
        - finger_r_joint20
